package com.jmm.brsap.meditell.util

enum class InteractionType{
    CALL,VISIT
}

enum class UserTypes{
    REPRESENTATIVE,DOCTOR,PHARMACY
}

enum class NavigationEnum{
    MANAGE_SCHEDULE,ADD_NEW_LOCATION,
    DAILY_CALL_RECORDING,ATTENDANCE_REGISTER,
    ADD_DOCTOR_PHARMACY,SEARCH_DOCTOR_PHARMACY,SEND_REPORT,
    SINGLE_DAY,WEEKLY
}